### ISSUE TITLE
EUNIMART - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#291]
1. Buyer App logs: 
a. Either payload isn't complete or isn't compliant with the protocol. Pls check the API contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit) and the logs submitted should have the complete payload as in the API contract for us to verify;
b. Buyer App should be tested with at least 2 other seller apps and the logs submitted;
2. Seller App logs:
a. Seller App should be tested with at least 2 other buyer apps (not Eunimart) and the logs submitted for us to verify;
3. Logistics: if you're planning to integrate with on-network logistics, pls test your seller app with at least 1 other logistics provider and submit logs for verification;

**Comment by BLR-0118** [comment]
@sridhareunimart

**Comment by BLR-0118** [comment]
For your reference:
1. [Retail API contract](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit)
2. [Logistics API contract](https://docs.google.com/document/d/1LiKGK3AKwzx5GWAc5g942QKB-TzDn0gGMsvXNJgIrmk/edit)
3. [Technical Compliance Checklist](https://docs.google.com/document/d/1jXkPwF-Fol9LeXbzQaC65R6UB60Cwc-cUiQ0qzsKNKQ/edit)

**Comment by sridhareunimart** [comment]
We've tested and raised a PR
https://github.com/ONDC-Official/verification-logs/pull/297

**Comment by BLR-0118** [comment]
1. Logs have to be submitted for verification from pre-prod;
2. Separate logs should be provided for buyer & seller app for both request & response;
3. Buyer App logs should be submitted with non-Eunimart seller app and the logs should comply with the API contract "to the tee";
4. Seller App logs should be submitted with non-Eunimart buyer app (preferably one of the prod buyer apps) and the logs should comply with the API contract "to the tee";

**Comment by BLR-0118** [comment]
@sridhareunimart

**Comment by sridhareunimart** [comment]
Submitted with new [PR](https://github.com/ONDC-Official/verification-logs/pull/396) Please check @BLR-0118

**Comment by BLR-0118** [comment]
Buyer App:
1. /search - Context.ttl should be "PT30S";
2. /init - 
- billing.areacode is invalid key;
- documents not valid key as per api contract;
3. /confirm -
- delivery_info is invalid key;
- payment.type changed from post-fulfillment (init) to pre-fulfillment here, how?
4. /update - not compliant with api contract;
5. No /support API?

**Comment by BLR-0118** [comment]
LSP BAP:
1. /confirm - Context is incomplete;
2. Context.ttl should be "PT30S" for all APIs

**Comment by BLR-0118** [comment]
@sridhareunimart

**Comment by sridhareunimart** [comment]
@BLR-0118 I've updated logs with BAP, BPP, LSP BAP

**Comment by BLR-0118** [comment]
Seller App:
1. /on_search:
- transaction_id & message_id doesn't match what's in search;
- category id used is invalid;
- extra keys used which are not compliant with API contract;
2. /on_select, on_init, on_confirm:
- item_id in quote.breakup for fulfillment level charges (delivery, packing) should be for the fulfillment id, not item id;
3. /on_confirm:
- no default fulfillment state;
4. /on_status:
- order state is invalid;
5. No /on_update?
6. /on_cancel:
- RTO fulfillment start time range isn't correct;

**Comment by BLR-0118** [comment]
@sridhareunimart

**Comment by sridhareunimart** [comment]
Buyer App:

/on_search:
category of garments is invalid;

----> on_search is from Seller app, can't do much <----

/select:
fulfillments.end.location.address.gps is invalid;

----> Seller side issue <----

/init:
payment.collected_by is "BAP" and type is post fulfillment (means buyer app is collecting after delivery), hence, settlement_details.settlement_counterparty should be seller app & should be defined by BPP, not BAP;

----> Seller side issue <----


/confirm:
payment type was post fulfillment (in init), here it's pre-fulfillment. How?

----> Fixed <----

no buyer app finder fee in payment block?

----> Seller side issue <----

/update:
not as per api contract;
uses order id different from what was created in /confirm, hence, difficult to verify;

----> No seller app to test for cancellation and update so tried with our own seller app <----

**Comment by sridhareunimart** [comment]
@BLR-0118

**Comment by sridhareunimart** [comment]
New [Pull Request](https://github.com/ONDC-Official/verification-logs/pull/422)

**Comment by BLR-0118** [comment]
1. /search:
- why's there a difference in precision between lat & lng gps coordinates?
2. /init:
- location.areacode is invalid key;
- payment."@ondc/org/settlement_details" should be filled up by BPP is BAP is collecting payment;
3. Why does context.city change from 040 in /search to 080 everywhere else. What does this mean?
4. /update API includes invalid keys (check item.tags)

**Comment by BLR-0118** [comment]
@sridhareunimart

**Comment by sridhareunimart** [comment]
@BLR-0118 update the logs with the comments, Please [check PR](https://github.com/ONDC-Official/verification-logs/pull/430)

**Comment by bluecypher** [comment]
**Eunimart BPP Issues:**

/on_search
quantity.available count can't be greater than quantity.maximum count
items catalog can't be empty for provider id SIVA-ONDC-STORE-2
Holidays are not updated for provider id SIVA-ONDC-STORE-2
Both fixed and split timings can't be provided for provider id SIVA-ONDC-STORE-2

/select
core_version changed from 1.1.0 to 1.0.0

/on_select
@ondc/org/TAT PT1M Shipping + delivery to be done in 1 minute?

/on_init
Buyer app finder type and amount can't change in /on_init

/on_cancel
Timestamp for /cancel and /on_cancel can't be same

/status
City code mismatch in /search and /status
Transaction Id for /select and /status api should be same
Order ids in /confirm and /status do not match

/on_status
City code mismatch in /search and /on_status
Transaction Id for /select and /on_status api should be same
Order id in /on_confirm and /on_status do not match
Fulfillment state Code (/on_status) should be as per the API Contract.


**Eunimart BAP Issues:**

/on_select
Quoted Price in /on_select does not match with the price of selected items in /select

/on_confirm
Quantity.maximum count in /on_init and /on_confirm do not match

/cancel
City code mismatch in /search and /cancel
Timestamp for /on_confirm api cannot be greater than /cancel api
Transaction Id for /select onwards APIs should be same
Order Id in /cancel and /on_confirm do not match

/on_cancel
City code mismatch in /search and /on_cancel
Timestamp for /on_confirm api cannot be greater than /on_cancel api
Transaction Id for /select and /on_cancel api should be same
Order id in /on_cancel and /on_confirm do not match

**Comment by bluecypher** [comment]
@sridhareunimart

**Comment by sridhareunimart** [comment]
@BLR-0118 @bluecypher we've updated logs accordingly

**Comment by sridhareunimart** [comment]
[Pull request](https://github.com/ONDC-Official/verification-logs/pull/437)

**Comment by sridhareunimart** [comment]
@BLR-0118 apologies.. I've forgot to update cancel and update logs.. I'll update it and inform

**Comment by bluecypher** [comment]
/on_search
locations.range.start not in correct format

/init
provider.locations can't be empty

/on_init
settlement_details should be provided by seller-app

/confirm
Order creation and updation timestamp not present

/on_confirm
Quote Object in /on_init and /on_confirm does not match

/cancel
Can't validate due to different transaction id

/on_cancel
Transaction Id for /select and /on_cancel api should be same
Order id in /on_cancel and /on_confirm do not match

/update
can't validate due to different txn id

@sridhareunimart

**Comment by sridhareunimart** [comment]
@bluecypher @BLR-0118 Updated logs.. please check..

**Comment by sridhareunimart** [comment]
[Pull Request](https://github.com/ONDC-Official/verification-logs/pull/449)

**Comment by bluecypher** [comment]
**Buyer - WithOtherSeller**

/on_select
fulfillment[].id should be of type string
provider id mismatches in /on_search and /on_select

/init
billing.address created_at and updated_at timestamps are invalid keys

/on_init
provider.id and provider_location.id mismatches in /on_search and /on_init

/on_confirm
order created_at and updated_at timestamps missing

/on_status
order.created_at timestamp can't change in on_status
order.timestamp can't change if order.state remains same.


**Buyer-WithOurSeller**

/on_select
fulfillments-@ondc/org/TAT PT1M?
'ttl' is a property of quote object 

/init
billing.address.created_at and billing.address.updated_at are invalid keys

/on_init
Billing object mismatches in /init and /on_init.
settlement counterparty should be seller_app when collected_by BAP.

/on_confirm
Default fulfillments state code and name should be used.
order.updated_at timestamp should be updated.

/on_status
Fulfillment State Code in /on_status is not as per the API Contract

**Buyer- WithOurSellerUnsolicited**

/on_update
quote.price should be 0 if the order.state is cancelled.

**Seller-WithOtherBuyer**

/on_select
'ttl' is a property of quote object.
fulfillments TAT=PT1M?

/on_init
Billing object mismatches in /init and /on_init
payment collected_by status should be "Agree"
settlement counterparty should be seller-app


/on_confirm
Default fulfillments state code and name should be used
order.updated_at timestamp should be updated.

No status, track and update APIs to validate


@sridhareunimart

**Comment by sridhareunimart** [comment]
@bluecypher [Pull request](https://github.com/ONDC-Official/verification-logs/pull/450) for Buyer - WithOtherSeller
Below are the comments:

/on_select
fulfillment[].id should be of type string
provider id mismatches in /on_search and /on_select
**Seller app side issue**

/init
billing.address created_at and updated_at timestamps are invalid keys
**Fixed**

/on_init
provider.id and provider_location.id mismatches in /on_search and /on_init
**Seller app side issue**

/on_confirm
order created_at and updated_at timestamps missing
**Seller app side issue**

/on_status
order.created_at timestamp can't change in on_status
order.timestamp can't change if order.state remains same.
**Seller app side issue**

**Comment by bluecypher** [comment]
@sridhareunimart 

/on_search
wrong payload submitted (different bpp_id)

Issues from seller app side still persist.

**Comment by sridhareunimart** [comment]
@bluecypher updated correct on_search payload

**Comment by sridhareunimart** [comment]
[Pull request](https://github.com/ONDC-Official/verification-logs/pull/453)

**Comment by BLR-0118** [comment]
Buyer App with Craftsvilla:
1. /search - why the difference in precision between lat/lng gps coords?
2. /init - fulfillment.end.location.country is empty;
3. /init - fulfillment.provider_id should be the bpp_id as per contract;
4. /confirm - payment is on-order and collected by BAP (means prepaid collection by buyer app, happens before sending /confirm), but no payment txn id?
5. /confirm - order.documents (for invoice) to be entered by seller app;
6. Is the [confirm [](flow](https://github.com/ONDC-Official/protocol-network-extension/discussions/28)) enabled?
7. No APIs for /update, /track?

**Comment by BLR-0118** [comment]
@sridhareunimart

**Comment by BLR-0118** [comment]
Seller App with ondc.indiastack.cloud
1. /on_search: seems to have been coded based on proposed spec, not on the basis of the retail API contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit#). Will get back on the changes required here;
2. /on_select: fulfillment TAT refers to O2D (order-to-delivery). Is this really 1 min (PT1M)?
3. /on_init: tags structure is invalid;
4. item available/max qty not in /on_search but in /on_init, /on_confirm (not compliant with contract);
5. /on_confirm - fulfillment state should be one of the post-order states (starting from "Pending");
6. Are there logs for /on_status (solicited, unsolicited) with some other buyer app, /on_update?

**Comment by BLR-0118** [comment]
@sridhareunimart

**Comment by sridhareunimart** [comment]
@bluecypher @BLR-0118 Please find updated logs [Pull request](https://github.com/ONDC-Official/verification-logs/pull/457)

**Comment by sridhareunimart** [comment]
/search - why the difference in precision between lat/lng gps coords?
**Issue Resolved**
/init - fulfillment.end.location.country is empty;
**Issue Resolved**
/init - fulfillment.provider_id should be the bpp_id as per contract;
**Issue Resolved**
/confirm - payment is on-order and collected by BAP (means prepaid collection by buyer app, happens before sending /confirm), but no payment txn id?
**Issue Resolved**
/confirm - order.documents (for invoice) to be entered by seller app;
**Issue Resolved**
Is the [confirm enabled?
**Issue Resolved**
No APIs for /update, /track?
**/update submitted**
/track - we couldn't submit as seller app's order tracking is false

@BLR-0118 @bluecypher

**Comment by BLR-0118** [comment]
Buyer-WithOtherSeller-Cancel logs:
Issue with provider id & location id
1. /select - provider id is 115050 & location id is 167341 (this is same as what's in /on_search); /on_select responds with provider id of 167340;
2. /init - provider id is 115050 & location id is 167341 (same as /select); /on_init responds with provider id of 167340 & location id of 157277;
3. /confirm - provider id is 167340 & location id is 157277 (same as /on_init);
Ideal behaviour here would be rejecting the /on_select and not progressing with /init. If buyer was shown & accepted this change, /init provider id & location id should have been same as /on_select as after ACK of /on_select, the order is effectively frozen;

Buyer-withOtherSeller-Update logs:
1. /update - existing contract doesn't have the reason_code block for part cancel, hence invalid;
2. No settlement block in /update for refund initiation?

**Comment by BLR-0118** [comment]
@sridhareunimart

**Comment by sridhareunimart** [comment]
@BLR-0118 Submitted with other seller app. Please check. [Pull request](https://github.com/ONDC-Official/verification-logs/pull/462)

**Comment by sridhareunimart** [comment]
@BLR-0118 @bluecypher Please review the seller app logs. [Pull request](https://github.com/ONDC-Official/verification-logs/pull/469)

**Comment by BLR-0118** [comment]
Buyer App:
1. /update - refund amount calculation is wrong. What's the logic used?
2. /confirm - fulfillment.end.person.name should be provided;
3. request to provide a return flow also in /update;
@sridhareunimart

**Comment by bluecypher** [comment]
/on_search
Based on proposed spec instead of retail API contract
bpp/providers[0].items[0].tags should be an object instead of array of objects.

/init
fulfillments[].provider_id for fulfillment SIVA-ONDC-STORE-FULFILLMENT-1 should be the bpp_id as per the contract

/on_init
Billing object mismatches in /init and /on_init (created and updated timestamps)

/on_confirm
fulfillments[].start.contact is missing

/status
City code mismatches in /confirm and /status

No /cancel and /on_cancel to validate 
No /update return flow

@sridhareunimart

**Comment by sridhareunimart** [comment]
@BLR-0118 @bluecypher Updated Buyer Seller and IGM Logs [Pull request](https://github.com/ONDC-Official/verification-logs/pull/472)

**Comment by bluecypher** [comment]
#### Eunimart BAP Cancel Flow

/confirm
fulfillments[0].end.person object is missing
fulfillments[0].customer is an invalid key

/on_confirm
order.updated_at timestamp should be updated when order state changes
Billing object mismatches in /confirm and /on_confirm

/on_cancel
150 is not of type 'string' in $.quote.breakup[4].price.value

/on_status
order timestamps not as per the API contract

#### Eunimart BAP Return Flow

/on_status
order.created_at timestamp mismatches in /confirm and /on_status
order.updated_at should change as per the order state

/update
order.state should be completed

/on_status (unsolicited)
fulfillments.state.descriptor.code should be "Order-delivered" 


#### Eunimart BAP with Other BPP

/on_select
quote.breakup item's unit price value can't be of type object

#### Eunimart BPP with other BAP
_Similar issues as mentioned above_


@sridhareunimart

**Comment by sridhareunimart** [comment]
@BLR-0118 @bluecypher Updated Latest Buyer Seller Logs [Pull request](https://github.com/ONDC-Official/verification-logs/pull/476)

**Comment by BLR-0118** [comment]
1. Pls submit logs for your buyer app with non-Eunimart seller app;
2. Pls comply with v1.1.0 of contract published yesterday;
3. Also, pls respond to the following scenarios:
- how does the buyer app respond to non-serviceable fulfillment state in /on_select?
- how does the buyer app respond to out-of-stock or price change in /on_select?
- how does the buyer app respond to out-of-stock or price change in /on_init?
- does the buyer app allow buyer to change delivery address to something different from the default address using which /search is initiated? if so, how does the buyer app respond?
- what is the /confirm flow? does it include retries as per the flow defined?
- what does the buyer app do if it receives NACK in /on_confirm?

**Comment by BLR-0118** [comment]
@sridhareunimart

**Comment by bluecypher** [comment]
Eunimart IGM Logs

Need to comply with current changes in the schema of API contract 

/issue
available and maximum count of product not required in /issue -- Order object updated in API Contract
created_at and updated_at timestamps naming error 
invalid agent object -- As per order object
invalid keys "name" and "code" in supplementary_information 
expected_response_time duration not in ISO 8601 format 
status.id and issue.id should be same

/on_issue
status.status should be "Resolved"

/on_issue_status
issue id mismatches in APIs 
modified_issue_field_name value is missing 
issue_status.status case sensitivity mismatch

@sridhareunimart

**Comment by sridhareunimart** [comment]
@BLR-0118 @bluecypher updated the [Pull request](https://github.com/ONDC-Official/verification-logs/pull/488).
Updated the contract according to [v1.1.0](https://docs.google.com/document/d/1fefHfMoYIouN-QJTDJFFZm46dqHmFvwY-6ICoISJcUY/edit#)

**Comment by BLR-0118** [comment]
Flow 1:
1. /on_search - there are 2 locations in the serviceability construct - SIVA-ONDC-STORE-1-LOC-1 & SIVA-ONDC-STORE-1-LOC-2. However, catalog has item for only the 1st location:
- Is the understanding that the 1st location is for grocery & 2nd for F&B?
- why is serviceability defined for both locations but store timings only for 1?
- Catalog has 1 grocery item which has veg/non-veg tag meant for F&B. Why?
2. why does the 1st search response take almost 5 secs but the 2nd takes about 300 ms (response time is computed as difference in context timestamp between response & request);
3. /select, /init, confirm - provider.locations.id: why is the same id shown twice?
4. /on_select - when the 2 items selected are from the same store location & have the same "time to ship", why is 2 separate fulfillments created?
5. /init, /on_init, /confirm - fulfillment.provider_id is deprecated;
6. /init - billing.created_at, billing.updated_at timestamp should match context timestamp;
7. /confirm - order.created_at, order.updated_at should match context timestamp;
8. /on_status (unsolicited_for_docs) - how did order.created_at suddenly change here? It should be the same as what was set in /confirm;
9. /on_status (unsolicited for status) - why does docs have 2 invoices here when only 1 was updated in the previous call;
10. /update - settlement timestamp (indicating when initiated) should be after Context.timestamp for /on_update where return request is approved for liquidated state;

Flow 2:
1. /on_init (flow - non serviceability) - error object should be outside Order;

Flow 4:
1. /select (out of stock) shows item.quantity.count of 5. /on_select (out of stock) shows quote.breakup."@ondc/org/item_quantity" of 5 => same as what was selected. Why is this out of stock?
2. /on_select (out of stock) - error object should be outside order;

**Comment by BLR-0118** [comment]
@sridhareunimart

**Comment by sridhareunimart** [comment]
Updated logs.. Please verify the [Pull request](https://github.com/ONDC-Official/verification-logs/pull/495) @BLR-0118 @bluecypher

**Comment by sridhareunimart** [comment]
Updated [logs](https://github.com/ONDC-Official/verification-logs/pull/499). Please verify @BLR-0118 @bluecypher

**Comment by BLR-0118** [comment]
Flow 1:
1. /search - buyer app finder fee type should be "percent" (lower case) in /search, /on_init, /confirm, on_confirm, /on_status;
2. inconsistency in area_code between /search & /init:
- /search gps is "gps": "17.4485835,78.3908034" & area_code is 500004;
- /init fulfillment.end.location.gps is ""17.4485835,78.3908034" but area_code is 500070. How?
3. fulfillment TAT in /on_select is P7D (7 days) but difference between start & end time range in /on_confirm & /on_status is 7 hrs. Should the fulfillment TAT in /on_select have been 7 hrs?
Flow 2:
1. Delivery location changes between /select & /init. In this case, the flow should be slightly different from what's shown here - /select should be called again (not init->on_init (with serviceability error)->select->on_select). This is because the (new) delivery location may be serviceable but the logistics cost & TAT could be very different and this has to be shown to the buyer at the time of checkout (i.e. after /on_select);
Flow 5:
1. /on_init (stock unavailable and price update) - quote.price is not matching the sigma of quote.breakup.price;

Please address the issues in Flow 1 & 2 and resubmit the logs only for flow 5.
Also, clarify whether Eunimart seller app support search by city?

**Comment by BLR-0118** [comment]
@sridhareunimart

**Comment by sridhareunimart** [comment]
Flow 1:

/search - buyer app finder fee type should be "percent" (lower case) in /search, /on_init, /confirm, on_confirm, /on_status;
**Issue fixed**

inconsistency in area_code between /search & /init:
/search gps is "gps": "17.4485835,78.3908034" & area_code is 500004;
/init fulfillment.end.location.gps is ""17.4485835,78.3908034" but area_code is 500070. How?
**Issue fixed and Validations added**

fulfillment TAT in /on_select is P7D (7 days) but difference between start & end time range in /on_confirm & /on_status is 7 hrs. Should the fulfillment TAT in /on_select have been 7 hrs?
**Issue Fixed**

Flow 2:
Delivery location changes between /select & /init. In this case, the flow should be slightly different from what's shown here - /select should be called again (not init->on_init (with serviceability error)->select->on_select). This is because the (new) delivery location may be serviceable but the logistics cost & TAT could be very different and this has to be shown to the buyer at the time of checkout (i.e. after /on_select);
**Issue Fixed**

Flow 5:
/on_init (stock unavailable and price update) - quote.price is not matching the sigma of quote.breakup.price;
**Issue fixed**

Please address the issues in Flow 1 & 2 and resubmit the logs only for flow 5.
**Done**

Also, pls clarify the following:

whether Eunimart seller app support search by city?
**Yes, We support the same**

signing & verification: has it been checked with other buyer/seller apps?
**Yes, we checked it with other NPs**


Please find the updated [pull request](https://github.com/ONDC-Official/verification-logs/pull/509)

@BLR-0118 @bluecypher

**Comment by BLR-0118** [comment]
1. One issue still remains:
The flow is: select1-> on_select1 -> init(stock_unavailable_price_update) -> on_init(stock_unavailable_price_update) -> select 2-> on_select2 -> init2 -> on_init2 -> etc.
This flow is correct but the transaction_id changes from select2 onwards. This probably means the buyer app is clearing the cart & asking buyer to select items again which is not correct. This will cause loss of state in this case:
- if the seller gave a discount or offer to buyer, this state will be lost as the seller will think this is a new buyer transaction.

**Comment by BLR-0118** [comment]
@sridhareunimart

**Comment by sridhareunimart** [comment]
@BLR-0118 @bluecypher updated logs as requested. [Pull request](https://github.com/ONDC-Official/verification-logs/pull/511)

**Comment by BLR-0118** [comment]
logs for retail buyer app & retail seller app (grocery, f&b) cleared

**Comment by BLR-0118** [comment]
@sridhareunimart
